<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251206162514 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, requested_quantity INT NOT NULL, reserved_quantity INT NOT NULL, order_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC9FF86B4584665A ON order_lines (product_id)');
        $this->addSql('CREATE INDEX idx_order_line_order ON order_lines (order_id)');
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shipped_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_order_status ON orders (status)');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5AF9038C4 ON products (sku)');
        $this->addSql('CREATE TABLE reservations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, order_line_id INT NOT NULL, warehouse_stock_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_reservation_order_line ON reservations (order_line_id)');
        $this->addSql('CREATE INDEX idx_reservation_warehouse_stock ON reservations (warehouse_stock_id)');
        $this->addSql('CREATE TABLE warehouse_stocks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, reserved_quantity INT NOT NULL, warehouse_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3A347745080ECDE ON warehouse_stocks (warehouse_id)');
        $this->addSql('CREATE INDEX idx_product ON warehouse_stocks (product_id)');
        $this->addSql('CREATE UNIQUE INDEX warehouse_product_unique ON warehouse_stocks (warehouse_id, product_id)');
        $this->addSql('CREATE TABLE warehouses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, location VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT FK_CC9FF86B8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT FK_CC9FF86B4584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA239BB01DC09 FOREIGN KEY (order_line_id) REFERENCES order_lines (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA2392D8503B6 FOREIGN KEY (warehouse_stock_id) REFERENCES warehouse_stocks (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_stocks ADD CONSTRAINT FK_B3A347745080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_stocks ADD CONSTRAINT FK_B3A347744584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_lines DROP CONSTRAINT FK_CC9FF86B8D9F6D38');
        $this->addSql('ALTER TABLE order_lines DROP CONSTRAINT FK_CC9FF86B4584665A');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA239BB01DC09');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA2392D8503B6');
        $this->addSql('ALTER TABLE warehouse_stocks DROP CONSTRAINT FK_B3A347745080ECDE');
        $this->addSql('ALTER TABLE warehouse_stocks DROP CONSTRAINT FK_B3A347744584665A');
        $this->addSql('DROP TABLE order_lines');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE reservations');
        $this->addSql('DROP TABLE warehouse_stocks');
        $this->addSql('DROP TABLE warehouses');
    }
}
